language: node_js

node_js:
  - "8"

install:
  - yarn install
#  - yarn global codecov

script:
  - yarn dev

after_script:
  - yarn build

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master
